version: "3.9"
services:
  app:
    image: python:3.12
    container_name: practica_app
    volumes:
      - ./src:/app
    working_dir: /app
    command: tail -f /dev/null  # Mantiene el contenedor corriendo
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: practica_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: practica
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
